---
abstract: 'Look up and display change logs of CPAN releases'
author:
  - 'Thomas Sibley <tsibley@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.1, Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-cpanchanges
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  File::Temp: 0
  Getopt::Long: 0
  JSON: 0
  LWP::UserAgent: 0
  URI::Escape: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/tsibley/App-cpanchanges/issues
  homepage: https://github.com/tsibley/App-cpanchanges
  repository: https://github.com/tsibley/App-cpanchanges.git
version: 20140125.0
x_contributors:
  - 'Olaf Alders <olaf@wundersolutions.com>'
